# .cursor/config/commit-rules.yaml
rules:
  commitTypes:
    feat:
      description: "New feature implementation"
      requireScope: true
      exampleScopes: ["auth", "ui", "billing"]
    fix:
      description: "Bug resolution in existing code"
      requireScope: false
    docs:
      description: "Documentation updates"
      validScopes: ["readme", "architecture", "api"]
    style:
      description: "Code formatting/whitespace changes"
      requireEslint: true
    refactor:
      description: "Code restructuring without behavior changes"
      requireTests: true
    test:
      description: "Test additions/modifications"
      validScopes: ["unit", "integration", "e2e"]
    chore:
      description: "Maintenance tasks"
      excludeScopes: ["migrations"]
