# .cursor/config/performance.yaml
storage:
  path: .cursor/performance/history/
  retention:
    L1D: 
      duration: 24h
      resolution: hourly
    L7D:
      duration: 7d
      resolution: daily

thresholds:
  critical:
    bundleSize: 500KB
    lcp: 2500ms
    dbQueryTime: 200ms
  warning:
    bundleSize: 450KB
    lcp: 2000ms